### PR TITLE
Make 'twitter::auth' public to expose 'twitter::auth::get' / 'twitter::auth::post'

### PR DESCRIPTION
**Pull request by mehcode**
I'm using the new `/direct_message/events/list` API from Twitter. I started to work on adding this in to `egg-mode` and I'm at a loss of how to work it in. It's a cursored collection but the cursor is in different format (string instead of integer) than other collections in Twitter.

This small change would allow me to take advantage of the underlying request/auth setup and parse the response myself until this library supports the events API.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
I'm afraid i can't accept this. Hiding the `auth` module was a deliberate design decision, because i didn't want to expose the OAuth mechanisms. (When i was originally writing egg-mode, this was out of frustration of having to wade through the numerous OAuth crates that claimed to provide generic OAuth functionality, but in practice were only written for a single site. I didn't want to add to the mess, so i pulled the connection/authentication code internal.)

Over time i've seen several forks that did exactly this, likely to do the same thing you wanted. I don't mind if you want to do this for your own code, but i can't accept this in egg-mode proper. I will accept a PR to `TODO.md` to add these endpoints if they're not already there, to get them on my radar. I wasn't aware of them until now. `>_>`

(Also, exposing `auth::{get, post}` is not enough to run custom endpoints. You'll also need to expose `RawFuture` or `make_future`/`make_parsed_future` to actually plug in the Request to the same machinery the rest of the library uses. These are *definitely* internal details that i'm not willing to expose, even more strongly than `get` or `post`.)

**Comment by QuietMisdreavus** [comment]
As for the DM Events API, it looks like the list endpoint is just a CursorIter, but DM Events would need to be a new struct, since it looks like they're different from the `DirectMessage` the old API uses. The biggest problem is that it looks like all the events endpoints require an `application/json` payload, which i haven't put in support for yet. Right now, all the endpoints that egg-mode exposes use `application/x-www-form-urlencoded` payloads, which `auth::post` constructs from the `ParamList` it's given.

I wonder if it would be easier to do #11 first, or just have some custom json constructor for these payloads. Regardless, the current `auth::post` is not built for these endpoints, and i believe the OAuth signing would also need to be tweaked as well? I haven't looked into it very much.

**Comment by mehcode** [comment]
> As for the DM Events API, it looks like the list endpoint is just a CursorIter,

The cursor is a string instead of an integer. The `Cursor` trait doesn't seem to support that.

> The biggest problem is that it looks like all the events endpoints require an application/json payload, which [...]

`application/x-www-form-urlencoded` works fine. I'm using it now.

---

> I'm afraid i can't accept this. [...]

Could I convince you to add a `.to_auth_header()` method (or similarly named) on `Token` ? The header generation is the most involved step. The rest I can do manually easily if I'm doing any endpoints outside of the supported ones.

**Comment by QuietMisdreavus** [comment]
> The cursor is a string instead of an integer. The `Cursor` trait doesn't seem to support that.

Oh wow, that's nasty. Then yeah, it would need to be a different kind of CursorIter, since it also doesn't seem to let you page backwards, either.

> `application/x-www-form-urlencoded` works fine. I'm using it now.

Oh, i guess i was looking at `POST direct_messages/events/new (message_create)` instead. `GET direct_messages/events/list` doesn't require json payloads, so that would work.

> Could I convince you to add a `.to_auth_header()` method (or similarly named) on `Token`?

All the auth items that aren't exported at the crate root are intended to be implementation details. I didn't want to bog my users down with the details of how i implemented OAuth (also because i was learning it myself, at the time), so i sealed it all off.

...however, if the auth module was cleaned up some (it was literally the first thing i wrote in egg-mode, which was one of my earliest rust projects `>_>`), if it were split into separate "how to get a token" and "internal-use methods" pieces, if that latter submodule had a big "you don't need to care about this" written into it, i think it's not entirely out of the question. But it would take more effort than just making the existing `auth` module public, or just adding hooks to existing infrastructure. I'm not comfortable exposing any of the underlying `auth.rs` or `common/response.rs` until i've had a chance to run through it. It's not up to the same standard as the stuff that's already public.

**Comment by mehcode** [comment]
Fair enough. I can deal with my fork that has `auth` exported until `events/list` is supported officially. I'll have no reason to use anything we add once `events/list` is supported anyway.

**Pull request closed without merging**
