### PR TITLE
Update to *ring* 0.9.4.

### PR DESCRIPTION
**Pull request by briansmith**
Before ring 0.9.3, it was possible to link multiple versions of ring into a program, e.g. if one version depended on ring 0.6 and another dependend on ring 0.9. Unfortunately, this doesn't work, because the linker doesn't know to how to link ring's C/asm code correctly in that kind of situation. ring 0.9.3 added a flag to its Cargo.toml to tell the Rust toolchain to stop allowing multiple versions of ring to be linked into the same program, to prevent any problems this may cause.

ring 0.9.4 was released with an update to make some crates easier to update to 0.9.x.

### CODE REVIEW

**Comment by briansmith** [comment]
Before ring 0.9.3, it was possible to link multiple versions of ring into a program, e.g. if one version depended on ring 0.6 and another dependend on ring 0.9. Unfortunately, this doesn't work, because the linker doesn't know to how to link ring's C/asm code correctly in that kind of situation. ring 0.9.3 added a flag to its Cargo.toml to tell the Rust toolchain to stop allowing multiple versions of ring to be linked into the same program, to prevent any problems this may cause.

ring 0.9.4 was released with an update to make some crates easier to update to 0.9.x.

**Comment by QuietMisdreavus** [comment]
Thanks for being proactive about this! I think I heard a rumbling about this on IRC recently, but didn't investigate. I'm glad that this could update without changing the code itself.

Two things:

- Could you take out the version bump to egg-mode itself? I leave that until right before a release. I don't know the standard way to handle version bumps, but I'd like to leave it like this until the next release, at least. Since I'm sitting on several feature changes since the last release, I don't want to release master as-is, so I'll leave this change here and backport it onto a new 0.8.x feature branch.
- As a sort of heads-up, I'm changing the license of egg-mode from Apache2.0 to MPL for version 0.9.0. Your change might not actually touch the code, but it's still an update to the crate itself, so I want to make sure you're okay with the license change when that drops.

**Comment by briansmith** [comment]
I updated the PR to remove the version bump for the egg-mode crate. I am happy to license this change under MPL 2.0 and/or what's listed as your current license.

**Comment by QuietMisdreavus** [comment]
Excellent! Thanks so much for reaching out!

**Pull request merged**
